cloud:
  aws:
    s3:
      bucket: ottokeng-dev-bucket
    credentials:
      accessKey: AKIATUZWCY6HVVZPXOOT
      secretKey: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false